all:
	makeinfo --html	\
		-o /var/www/slcc/onlinedocs/master/	\
		--css-ref=/onlinedocs/styles/slcc.css \
		--css-ref=/onlinedocs/styles/texinfo.css \
		-D 'VERSION 0.1' -D 'UPDATED 0.1' \
		/var/www/slcc/onlinedocs/texi/slcc.texi

